name: build-deploy
run-name: Build ${{ github.repository }}

on:
  release:
    types: [published]
  push:

jobs:
  build-and-deploy:
    name: Build and deploy
    uses: chukysoria/workflows/.github/workflows/build-image.yml@059ffb38edd65c05615494be32f81b111cfb0cc6 # v1.1.3
